emcc-hello-build:
	@echo "Building WASM Hello.cc ..."
	@echo "编译之后的成果为: hello.wasm, hello.js"
	emcc hello.cc -o hello.js

emcc-hello-build-html:
	@echo "Building WASM Hello.cc ..."
	@echo "编译之后的成果为: hello.wasm, hello.js, hello.html"
	emcc hello.cc -o hello.html
